spring:
  # 스프링 설정: datasource
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://125.159.61.195:40015/aib2b
    username: genieb2b
    password: genie123

# WAS서버 설정
server:
  port: 8090
  connection-timeout: 10000

# Mybatis 설정
mybatis:
  #  config-location: classpath:config.mybatis.xml
  mapper-locations: classpath:sqlmaps/**/*.xml

# 사용자 변수
test:
  base: prod-base-value