#spring:
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#  # 스프링 설정: datasource
#  #mysqlds:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_db
#    username: root
#    password: welcome
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:postgresql://192.168.169.128:5432/testdb
#    username: postgres
#    password: welcome
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:postgresql://125.159.61.195:40015/aib2b
#    username: genieb2b
#    password: genie123
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/tutorial
#    username: root
#    password: 1234
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  mysqlds:
#    datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://192.168.169.130:3306/test_db
#      username: user1
#      password: test1234

#redis:
#  hostname: 192.168.169.129
#  port: 6379
#  database: 1000
#  password: thkim123
#  timeout: 5000

# WAS서버 설정
server:
  port: 8091
  connection-timeout: 10000

# Mybatis 설정
#mybatis:
#  config-location: classpath:config.mybatis.xml
  #mapper-locations: classpath:sqlmaps/**/*.xml

# 사용자 변수
test:
  base: test-base-value

#


